name: Run Model Predictions

on:
  push:
    branches:
      - main

jobs:
  run-predictions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install requirements for prediction
        run: |
          pip install -r requirements_predict.txt

      - name: Run prediction script
        run: |
          python models/model1/predict.py

      - name: Display script output
        run: |
          echo "Script output displayed above."
