name: Test Actions

on:
  push:
    branches:
      - main

jobs:
  test-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test GitHub Actions
        run: |
          echo "GitHub Actions are working!"
